from sqlmodel import SQLModel, Field
from typing import Optional
from datetime import datetime


class Playlist(SQLModel, table=True):
    """
    A user-owned playlist — either generated by the NOX curation engine,
    blended from multiple users, or manually assembled.

    tracks: JSON list of TrackItem dicts:
      [{name, artist, preview_url, album_art, score, matching_tags}]
    """

    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="user.id", index=True)

    name: str
    description: Optional[str] = Field(default=None)

    # How was this playlist created?
    # "nox_engine" | "lastfm_blend" | "manual" | "blend"
    source: str = Field(default="nox_engine")

    # JSON list of track objects
    tracks: str = Field(default="[]")

    created_at: datetime = Field(default_factory=datetime.utcnow)
